name: hubstaff-reports-cluster

services:
  hubstaff-reports:
    container_name: hubstaff-reports
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8100:8000
    volumes:
      - ./config.yaml:/app/config.yaml
    command: fastapi run app/main.py
    restart: always
